/**
 * Generates out/sw.js after `next build`.
 *
 * The precache list is read off the built output rather than hand-maintained,
 * so every one of the 87 day pages, all 50 exercise pages and every JS and CSS
 * chunk is guaranteed to be in it. R6 says the site works offline once
 * visited; that only holds if nothing is missed.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';

const OUT = 'out';

function walk(dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, acc);
    else acc.push(full);
  }
  return acc;
}

const files = walk(OUT);
const hash = createHash('sha256');

/** Needed before the app is usable at all: shell, chunks, fonts, icons. */
const core = [];
/** The program itself. Wanted offline, but not worth blocking the first paint. */
const rest = [];
let coreBytes = 0;
let restBytes = 0;

for (const file of files.sort()) {
  const rel = relative(OUT, file).split('\\').join('/');
  if (rel === 'sw.js' || rel.endsWith('.txt') || rel.endsWith('.map')) continue;
  // The illustration gallery is a review surface, not part of the product.
  if (rel.startsWith('dev/')) continue;

  const size = statSync(file).size;
  hash.update(rel);
  hash.update(String(size));

  let url;
  if (rel.endsWith('.html')) {
    if (rel === 'index.html') url = '/';
    else if (rel === '404.html') url = '/404.html';
    else url = '/' + rel.replace(/\.html$/, '');
  } else {
    url = '/' + rel;
  }

  // Day and exercise pages are the bulk; everything else is the shell.
  if (url.startsWith('/day/') || url.startsWith('/exercise/')) {
    rest.push(url);
    restBytes += size;
  } else {
    core.push(url);
    coreBytes += size;
  }
}

const version = hash.digest('hex').slice(0, 12);

const sw = `/* Generated by scripts/build-sw.mjs. Do not edit. */
const VERSION = '${version}';
const CACHE = 'nationals-' + VERSION;
const CORE = ${JSON.stringify(core)};
const REST = ${JSON.stringify(rest)};

async function fill(cache, urls, batchSize) {
  for (let i = 0; i < urls.length; i += batchSize) {
    await Promise.all(
      urls.slice(i, i + batchSize).map((url) =>
        cache.add(new Request(url, { cache: 'reload' })).catch(() => {
          // One missing file must not abort the whole install.
        }),
      ),
    );
  }
}

// Install blocks only on the shell, so the first visit is not held up by
// downloading twelve weeks of pages over 4G.
self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      await fill(cache, CORE, 12);
      await self.skipWaiting();
    })(),
  );
});

// Activate: drop old versions, then pull the rest of the program down in the
// background so every day page and every illustration is there offline.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
      await self.clients.claim();
      const cache = await caches.open(CACHE);
      await fill(cache, REST, 6);
    })(),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Hashed build assets never change under the same name: cache first, always.
  if (url.pathname.startsWith('/_next/static/')) {
    event.respondWith(
      caches.match(request).then((hit) => hit || fetch(request).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(request, copy));
        return res;
      })),
    );
    return;
  }

  // Pages: serve from cache immediately so a day page opens instantly in a
  // basement, and refresh in the background for the next visit.
  if (request.mode === 'navigate' || request.destination === 'document') {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE);
        const key = url.pathname.replace(/\\/$/, '') || '/';
        const hit = (await cache.match(key)) || (await cache.match(request));
        const network = fetch(request)
          .then((res) => {
            if (res.ok) cache.put(key, res.clone());
            return res;
          })
          .catch(() => null);
        return hit || (await network) || (await cache.match('/404.html')) || Response.error();
      })(),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request).catch(() => Response.error())),
  );
});
`;

writeFileSync(join(OUT, 'sw.js'), sw);
const mb = (n) => (n / 1024 / 1024).toFixed(2);
console.log(
  `sw.js ${version}: shell ${core.length} entries (${mb(coreBytes)} MB, blocking) + ` +
    `program ${rest.length} entries (${mb(restBytes)} MB, background)`,
);
